{% set name = "arm_pyart" %}
{% set version = "1.10.1" %}
{% set sha256 = "a88ef49c505b9911f217117ce2e88e3ba5547c4b8662920802ba0aee9cf8dabc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 0
    script:  # [not win]
      - export RSL_PATH=$PREFIX  # [not win]
      - "{{ PYTHON }} -m pip install . --no-deps -vvv"  # [not win]

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python
        - pip
        - numpy
        - trmm_rsl  # [not win]
    run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy
        - matplotlib
        - netcdf4
        - trmm_rsl  # [not win]

test:
    imports:
        - pyart

about:
    home: http://arm-doe.github.io/pyart/
    license: BSD-3-Clause
    summary: "Python ARM Radar Toolkit"

extra:
    recipe-maintainers:
        - jjhelmus
        - zssherman
