{% set name = "arm_pyart" %}
{% set version = "1.9.0" %}
{% set sha256 = "5dcd511a0dd7a76511d4e67f13d98e71a63f4927b988c03ca277a7d379387bcc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    number: 0

requirements:
    build:
        - python
        - numpy x.x
        - trmm_rsl  # [not win]

    run:
        - python
        - numpy x.x
        - scipy
        - matplotlib
        - netcdf4
        - trmm_rsl  # [not win]

test:
    imports:
        - pyart

about:
    home: http://arm-doe.github.io/pyart/
    license: BSD-3-Clause
    summary: "Python ARM Radar Toolkit"

extra:
    recipe-maintainers:
        - jjhelmus
