travis:
  secure:
    BINSTAR_TOKEN: eXor1zfdc/ulzC0WAX/MteUHeddW/up9zR6R41IQ/rEet+wv4HhI/AjlS0/cwGdCT0MSWglpwd2CXggeoVHyu95kmfnfpU6X8PkYuHIUtH0S0dkOYrVlgABnOhtC37dAj0IoRSsEmOYTM5hUCTzUQhAIVXgxw06EC+kIKmbU/Jxi8xuvwYgfRJT1uhufNnVke44M89He6XjvR2bRMP56RMOopf0k5TQoduobdM3gUT/Z/glqpz99mhWrayt7c4eZYKR+vJZAfohdd6YVy6UOubl5sN0dzFazZCQT8CbUSH1EaZfhVqOdEdblE4jfWUlOSZMzRk8GfN4+DdhbqAtJoOt8UgILOJOb80QxREjR41nUbOucB4tQg1CLV6hf/4xm8jiGZlJm+v2y9nyCofE2dOstI5jPEoCpDTo0j/6WiNnkW17ZpsZuaOWDMAJNh4alLFdYr50vu0dchR13Wuhr9Sk7hRqdDOQ02Tll8W0xvAode93Y9LbkTRLlXUMy8WJr8n0pWM3ZRf2Mh3aSWaaIH6YSl4405/Pkwc3ETiMBTS0w6fbbxWlrp/+4JmmsbSHnH/ilqqaSd48gkfveu4ryWNuXaGfUFG/vocG2yRPKktxW/MavVDClPwNeBBT2kGL7y0y8SVWAPuXBUXcCZFVQFBuEmP9ULhXeQPOOMeLZJJY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
